-- drop table if exists entries;
-- create table entries (
-- id integer primary key autoincrement,
--   name text not null,
--   lastname text not null,
--   rut text not null,
--   email text not null,
--   photo text not null default "",
--   score integer not null default 0,
--   played boolean not null default 0,
--   called boolean not null default 0
-- );