-- drop table if exists entries;
-- create table entries (
-- id integer primary key autoincrement,
--  name text not null,
--  lastname text not null,
--  rut text not null,
--  email text not null,
--  photo text,
--  score integer not null default 0,
--  rewarded boolean not null default false
--);
